// Code generated by protoc-gen-go.
// source: db.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	db.proto

It has these top-level messages:
	Record
	Pair
	Value
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Record struct {
	Values  []*Value `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	Type    int32    `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Current int64    `protobuf:"varint,3,opt,name=current" json:"current,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Record) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type Pair struct {
	Values []*Value `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	Key    []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Type   int32    `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
}

func (m *Pair) Reset()                    { *m = Pair{} }
func (m *Pair) String() string            { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()               {}
func (*Pair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Pair) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type Value struct {
	Unicode []byte `protobuf:"bytes,1,opt,name=unicode,proto3" json:"unicode,omitempty"`
	Numeric int64  `protobuf:"varint,2,opt,name=numeric" json:"numeric,omitempty"`
	Rev     int64  `protobuf:"varint,3,opt,name=rev" json:"rev,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Record)(nil), "azmodb.Record")
	proto.RegisterType((*Pair)(nil), "azmodb.Pair")
	proto.RegisterType((*Value)(nil), "azmodb.Value")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x49, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xac, 0xca, 0xcd, 0x4f, 0x49, 0x52, 0x8a, 0xe5, 0x62,
	0x0b, 0x4a, 0x4d, 0xce, 0x2f, 0x4a, 0x11, 0x52, 0xe5, 0x62, 0x2b, 0x4b, 0xcc, 0x29, 0x4d, 0x2d,
	0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0xe2, 0xd5, 0x83, 0x28, 0xd1, 0x0b, 0x03, 0x89, 0x06,
	0x41, 0x25, 0x85, 0x84, 0xb8, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x58,
	0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xe4, 0xd2, 0xa2, 0xa2, 0xd4, 0xbc, 0x12, 0x09, 0x66,
	0xa0, 0x30, 0x73, 0x10, 0x8c, 0xab, 0x14, 0xcc, 0xc5, 0x12, 0x90, 0x98, 0x59, 0x44, 0xac, 0xe1,
	0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x60, 0xb3, 0x79, 0x82, 0x40, 0x4c, 0xb8, 0x75, 0xcc, 0x08,
	0xeb, 0x94, 0x7c, 0xb9, 0x58, 0xc1, 0xda, 0x40, 0xf6, 0x96, 0xe6, 0x65, 0x26, 0xe7, 0xa7, 0xa4,
	0x02, 0x8d, 0x05, 0x69, 0x81, 0x71, 0x41, 0x32, 0x79, 0xa5, 0xb9, 0xa9, 0x45, 0x99, 0xc9, 0x60,
	0xc3, 0x80, 0x2e, 0x82, 0x72, 0x41, 0x56, 0x14, 0xa5, 0x96, 0x41, 0xdd, 0x09, 0x62, 0x3a, 0xb1,
	0x44, 0x31, 0x15, 0x24, 0x25, 0xb1, 0x81, 0xc3, 0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x24,
	0x48, 0x6c, 0x7e, 0x23, 0x01, 0x00, 0x00,
}
